services:
  - type: web
    name: f1ui-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
